"""empty message

Revision ID: 7fbf703216c8
Revises: b1ef3b8c974a
Create Date: 2016-01-17 20:45:40.192660

"""

# revision identifiers, used by Alembic.
revision = '7fbf703216c8'
down_revision = 'b1ef3b8c974a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
