"""empty message

Revision ID: 2e467629a577
Revises: bff4c0ae3549
Create Date: 2016-05-15 15:55:58.949971

"""

# revision identifiers, used by Alembic.
revision = '2e467629a577'
down_revision = 'bff4c0ae3549'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('w_animes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('bname', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=164), nullable=True),
    sa.Column('liked_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('w_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('bname', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=164), nullable=True),
    sa.Column('liked_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('w_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('bname', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=164), nullable=True),
    sa.Column('liked_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('w_movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('bname', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=164), nullable=True),
    sa.Column('liked_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('w_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('bname', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=164), nullable=True),
    sa.Column('liked_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('w_photos')
    op.drop_table('w_movies')
    op.drop_table('w_courses')
    op.drop_table('w_articles')
    op.drop_table('w_animes')
    ### end Alembic commands ###
