"""empty message

Revision ID: bff4c0ae3549
Revises: 5a47c103cab5
Create Date: 2016-05-15 11:46:21.290783

"""

# revision identifiers, used by Alembic.
revision = 'bff4c0ae3549'
down_revision = '5a47c103cab5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animes', sa.Column('bname', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('bname', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('bname', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('bname', sa.Text(), nullable=True))
    op.add_column('photos', sa.Column('bname', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'bname')
    op.drop_column('movies', 'bname')
    op.drop_column('courses', 'bname')
    op.drop_column('articles', 'bname')
    op.drop_column('animes', 'bname')
    ### end Alembic commands ###
