"""empty message

Revision ID: 58cac190db24
Revises: 7fbf703216c8
Create Date: 2016-01-17 21:00:11.417965

"""

# revision identifiers, used by Alembic.
revision = '58cac190db24'
down_revision = '7fbf703216c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    ### end Alembic commands ###
