"""empty message

Revision ID: 590f79da7609
Revises: 34f4edccd28b
Create Date: 2016-01-22 00:39:57.484536

"""

# revision identifiers, used by Alembic.
revision = '590f79da7609'
down_revision = '34f4edccd28b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_comments_timestamp'), 'comments', ['timestamp'], unique=False)
    op.drop_index('ix_comments_body_html', table_name='comments')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_comments_body_html', 'comments', ['body_html'], unique=False)
    op.drop_index(op.f('ix_comments_timestamp'), table_name='comments')
    op.drop_column('comments', 'timestamp')
    ### end Alembic commands ###
