"""empty message

Revision ID: 946e0ec958a2
Revises: 5658d894a341
Create Date: 2016-01-18 17:12:31.971460

"""

# revision identifiers, used by Alembic.
revision = '946e0ec958a2'
down_revision = '5658d894a341'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
